### ISSUE TITLE
Intercept breaks Ingress routing if backendServicePort is referenced by name

### ISSUE THREAD

**Issue by conneryn** [c6o/roadmap#32]
### Summary:

When an ingress controller references it's backend service, it must specify the backend port.  However, this backend port can be an explicit port number, or a reference to a named port on the related service.  Currently, the intercept service duplicates the existing service port number, but does not preserve the port name, therefore any ingress that references the backend service port via name will fail when an intercept is active.

### To Reproduce:

Create an ingress resource that references the backend service port by name, instead of by the port number explicitly.

```yaml
# Service
apiVersion: v1
kind: Service
metadata:
  name: example
spec:
  selector:
    // ...
  ports:
  - name: my-port-name
    port: 8080
    protocol: TCP
    targetPort: http

# Ingress
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example
spec:
  rules:
  - http:
      paths:
      - path: "/"
        backend:
          serviceName: example
          servicePort: my-port-name
```

Then intercept the service, and observe that the ingress controller can no longer route to the backend service.

### Observed Results:
The service is no longer available via the ingress controller, whether the intercept header is provided or not.

### Expected Behavior:
Intercept should work as intended.
